image: python:3.8
  pipelines:
    # branches:
    #   master:
    #     - step:
    #         name: Build & Test Python App
    #         image: python:3.8
    #         caches:
    #           - pip
    #         script:
    #           - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    custom:
      staging:
        - step:
            name: Build & Test Python App
            caches:
              - pip
            script:
              - if [ -f requirements.txt ]; then pip install -r requirements.txt -t /pycache; fi
            artifacts:
            - /pycache/**
        - step:
            name: Building The App
            deployment: Test
            script:
              - pipe: atlassian/aws-sam-deploy:1.3.1
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  S3_BUCKET: 'bitbucketpipelinesfastapi'
                  STACK_NAME: 'bitbucket'
                  DEBUG: 'true'
                  COMMAND: 'package-only'
                  SAM_TEMPLATE: 'template.yml'
                  SAM_CONFIG: 'samconfig.toml'

              - pipe: atlassian/aws-s3-deploy:0.3.2
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  S3_BUCKET: 'bitbucketpipelinesfastapi'
                  LOCAL_PATH: 'pycache'

              - pipe: atlassian/aws-s3-deploy:0.3.2
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  S3_BUCKET: 'bitbucketpipelinesfastapi'
                  LOCAL_PATH: '.bitbucket/pipelines/generated/pipeline/pipes/atlassian/aws-sam-deploy'
                  EXTRA_ARGS: '--exclude=* --include=packaged.yml'

              - pipe: atlassian/aws-sam-deploy:1.3.1
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  STACK_NAME: 'bitbucket'
                  TEMPLATE: 'https://s3.amazonaws.com/bitbucketpipelinesfastapi/packaged.yml'
                  CAPABILITIES: ['CAPABILITY_IAM', 'CAPABILITY_AUTO_EXPAND']
                  COMMAND: 'deploy-only'


