pipelines:
  branches:
    master:
      - step:
          name: Build & Test Python App
          image: python:3.8
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  custom:
    staging:
      - step:
          name: Building The App
          deployment: Test
          script:
            - pipe: atlassian/aws-sam-deploy:1.3.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KE
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: 'samgithubactions'
                STACK_NAME: 'bitbucket'
                DEBUG: 'true'
                COMMAND: 'all'
                CAPABILITIES: '[CAPABILITY_IAM]'
                SAM_TEMPLATE: 'template.yml'


