version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bitbucket-app"
s3_bucket = "bitbucketpipelinesfastapi"
s3_prefix = "bitbucket"
region = "ap-south-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

